ci: forbid yaml

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -42,6 +42,16 @@ jobs:
       - name: Lint yaml files
         uses: ibiqlik/action-yamllint@v3.1.0
 
+      - name: Check for .yml files
+        run: |
+          if git ls-files '*.yml' | grep -q .; then
+            echo "::error::'.yml' file extension is forbidden. Use '.yaml' instead."
+            git ls-files '*.yml'
+            exit 1
+          else
+            echo "✅ No .yml files found."
+          fi
+
   lint-branch-name:
     runs-on: ubuntu-latest
     if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
